spring:
  application:
    name: loans-context

  datasource:
    url: jdbc:postgresql://localhost:5432/loans_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090




