services:
  accounts:
    image: "rondocker2191/accounts:v2"
    container_name: accounts-ms
    ports:
      - 8085:8085
    deploy:
      resources:
        limits:
          memory: 770m
    networks:
      - anyname
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - anyname
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  anyname:
    driver: bridge

volumes:
  postgres_data: