server:
    port: 8085

spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testDB
        username: root
        password: password
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update # Automatically updates the database schema based on your entity classes
        database-platform: org.hibernate.dialect.H2Dialect
    application:
      name:
          accounts-context