server:
    port: 8085

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    application:
      name:
          accounts-context

accounts:
    name: rohit
    email: rohit@gmail.com
    phone: 923401992192

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
        health:
            probes:
                enabled:true