package com.rohit.accounts.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Accounts extends BaseEntity {

    // here we are not using data from lombok because we dont wnat hascode tostring for entities.

    @Id
    @Column(name = "account_number")
    private Long accountNumber; // the account number will be generated by some logic hence no geneneration types

    @Column(name = "customer_id") //
    private Long customerId;

    @Column(name = "account_type")
    private String accountType;

    @Column(name = "branch_address")
    private String branchAddress;
}
